# Generated by Django 5.0.6 on 2024-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_options_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to='images/', verbose_name='Загрузите фото товара'),
        ),
    ]
