# Generated by Django 5.0.6 on 2024-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier_price',
            field=models.IntegerField(default=0),
        ),
    ]
