# Generated by Django 5.0.6 on 2024-06-07 02:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0028_client_age_alter_carextradition_date_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_ordered',
            new_name='is_sold',
        ),
        migrations.RemoveField(
            model_name='car',
            name='daily_price',
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday_date',
            field=models.DateField(default='2000-01-01', validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 6, 12), message='Для регистрации необходимо достичь 18 лет')]),
        ),
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('promocode', models.CharField(max_length=30, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental_service_app.car')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_sales', to='car_rental_service_app.client')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental_service_app.discount')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental_service_app.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='CarExtradition',
        ),
    ]
