# Generated by Django 5.0.6 on 2024-06-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_service_app', '0029_rename_is_ordered_car_is_sold_remove_car_daily_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsale',
            name='final_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
