# Generated by Django 5.0.6 on 2024-05-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name_plural': 'Deals'},
        ),
    ]
