# Generated by Django 5.0.6 on 2024-05-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_discount',
            field=models.IntegerField(default=0),
        ),
    ]
