# Generated by Django 5.0.6 on 2024-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_current_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_discount',
            field=models.IntegerField(default=0),
        ),
    ]
