# Generated by Django 5.0.6 on 2024-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_usedusercoupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
