# Generated by Django 5.0.6 on 2024-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
