# Generated by Django 5.0.6 on 2024-05-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/Задняя_ось.jpg', upload_to='images/', verbose_name='Загрузите фото товара'),
        ),
    ]
